spring:
  datasource:
    name: production
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    schema: classpath:databases/uuu.sql
    continue-on-error: true
    initialization-mode: always
    sql-script-encoding: utf-8

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
    queue-name: directQueue
#        acknowledge-mode: manual

mybatis:
  type-aliases-package: com.giovanny.study.entity.po.Uuu
  mapper-locations: classpath*:mapping/*.xml


log:
  path: ./log/
  level: info
executor:
  corePoolSize: 50
  maximumPoolSize: 60
  keepAliveTime: 60
  queueSize: 50

